export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_GADGETS: "SET_GADGETS",
    SET_FOODS : "SET_FOODS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SELECTED_GADGET: "SELECTED_GADGET",
    SELECTED_FOOD : "SELECTED_FOOD",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};