export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_GADGETS: "SET_GADGETS",
    SET_CART: "SET_CART",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SELECTED_GADGET: "SELECTED_GADGET",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};